### ISSUE TITLE
Error building react-native app in Xcode

### ISSUE THREAD

**Issue by iandonov** [microsoft/clarity-apps#1]
>yarn add react-native-clarity
 "react-native-clarity": "^0.0.2"

>pod install
Installing react-native-clarity (0.0.2)

Build in Xcode (Version 14.3 (14E222b))
I get this error: 
Library not found for -lreact-native-clarity

Any idea what is wrong and how to fix it?

Thanks

**Comment by nouranmaher86** [comment]
Microsoft Clarity React Native SDK only supports the Android part for these cross platform stacks for now (React Native, Cordova, Ionic).
We will be updating the docs to mention this explicitly

**Comment by ibradwan** [comment]
Documentations have been updated.
