### ISSUE TITLE
Could not invoke Clarity.initialize

### ISSUE THREAD

**Issue by manuelTate** [microsoft/clarity-apps#13]
Hello.

Following the installation guide and documentation, I've been setting up clarity on a react-native application. 
Upon reaching the initialize function, the application crashes with the following error:

![Screenshot_20230721-121107_eMove - Debug](https://github.com/microsoft/clarity-apps/assets/92169769/0c7e64bb-29c6-43f0-a3fa-359901fd4e9b)

This is a snippet of the faulty code:
```js
import { initialize } from 'react-native-clarity'

...

if (IS_PRODUCTION && Platform.OS === 'android') initialize(CLARITY_PROD_ID, undefined, 'Verbose')
```
The application runs smoothly again by commenting said part of the code.

Is there something I'm missing on the Android setup part? I've tried to rebuild the application multiple times already. However, every time the same error shows up.

This is other data that may be key to the resolution of this bug:
- Version: 0.0.5
- Framework: ReactNative

There are sadly no runtime logs as the application crashes before being initialized.
Thank you in advance.

**Comment by maryamshal** [comment]
Hello Manuel, 
Please use [gradle](https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html) to upgrade the androidx.work dependency to atleast 2.8.1. This should resolve your issue.

**Comment by manuelTate** [comment]
Yup, it worked like charm. Thank you! 🙌
