### ISSUE TITLE
Is it possible to add tags using the react native package?

### ISSUE THREAD

**Issue by joaovcarvalho** [microsoft/clarity-apps#14]
It seems like the method set available in the web is not available for the package react-native-clarity. 

Is that something you guys are planning to add?

I would be interested in testing it.

**Comment by ibradwan** [comment]
Yes the feature has been implemented and should be shipped in our next release. So please stay tuned :)

**Comment by ibradwan** [comment]
This has been addressed in 1.0.1 please upgrade and let us know your experience.
