### ISSUE TITLE
Clarity supports android only for now

### ISSUE THREAD

**Issue by oguzydz** [microsoft/clarity-apps#16]
It's nice to be informed, but being warned repeatedly is annoying. I thought about removing it manually. However, it might also raise awareness for others.

<img width="422" alt="image" src="https://github.com/microsoft/clarity-apps/assets/36233491/e3ff616d-0928-4964-b7ff-456151b90551">

**Comment by CMLCNL** [comment]
We want to use clarity for ios. Is there any information about when it will be published?

**Comment by ibradwan** [comment]
@CMLCNL Thanks for your interest in Clarity. We are actively working on the iOS package. If you are interested and would like to be considered for our private preview, please send us more details about your application to clarity-apps-support@microsoft.com (with "Private Preview Client" in the subject).

**Comment by markymc** [comment]
I also find this warning to be annoying and feel it's not necessary.

Also thanks for the info on the iOS preview. Have just applied.

**Comment by nouranmaher86** [comment]
Please fill this form to join our early access list for viewing iOS SDK:
https://forms.microsoft.com/r/Rdy94iErqB

**Comment by obayit** [comment]
Is there a way to hide this warning?

**Comment by loewj-reekon** [comment]
@obayit You can conditionally initialize and call Clarity functions using `Platform.OS === 'android'`.

**Comment by ibradwan** [comment]
iOS support has been released.

**Comment by IanLukeFinley** [comment]
I note however that, as ov version 3.0.0, which I believe is the latest, the SupportedPlatforms in index.ts is still 'android' only, so the error appears, even when enableIOS_experimental is true in the config. 
![image](https://github.com/user-attachments/assets/282b6e25-3269-4f10-82c1-b53201cf2f99)

**Comment by ibradwan** [comment]
Thanks @IanLukeFinley for reporting that. @amralaa-MSFT Can you please double check?

**Comment by amralaa-MSFT** [comment]
@IanLukeFinley the `ios` value gets added to `SupportedPlatforms` only after `initialize()` is called. Could you please double check that your app doesn't use other Clarity APIs before `initialize()` is called?

**Comment by IanLukeFinley** [comment]
Yes, the issue seems to be the NavigationContainer in our App.tsx, which calls setCurrentScreenName before Initialize, when structured as you lay out in the [readme](https://www.npmjs.com/package/react-native-clarity). By removing the call for setCurrentScreenName from onReady, the flow happens in the correct order.

**Comment by ibradwan** [comment]
This issue has been fixed in a recent release.
