### ISSUE TITLE
How to stop clarity to collect data

### ISSUE THREAD

**Issue by OndrejMalek** [microsoft/clarity-apps#18]
Duplicate of https://github.com/microsoft/clarity/issues/75

We are facing performance issues in our Android app. I would be great to have any means to stop Clarity, disable Clarity at runtime. I was trying to not call `Clarity#initialize` during app startup, but this takes days to take effect at some users.

**Comment by ibradwan** [comment]
Hi @OndrejMalek,

Could you please let us know your project id to see what we can do?

**Comment by ibradwan** [comment]
Also can you please elaborate more on the perf issues you are facing with Clarity?
