### ISSUE TITLE
New build required with Expo & react-native-clarity ?

### ISSUE THREAD

**Issue by Nxtra** [microsoft/clarity-apps#19]
I have a react native app with expo.

When I follow the react native procedure to install clarity for my Expo app, will I need to do a new app bundle / new eas build? 

Or is this lib JS only and can I ship it with Expo.Update (without going through the stores)

**Comment by ibradwan** [comment]
Hi @Nxtra,

The Clarity plugin depends on native code to run. Therefore, you have to create a new build.

**Comment by markymc** [comment]
@ibradwan I just installed Clarity in my Expo app and it wasn't clear to me what's needed for Expo. I had to dig into the code to check if I needed any binary updates. I'd suggest you update the contents of https://www.npmjs.com/package/react-native-clarity?activeTab=readme to make it more clear what's needed for Expo users (as I suspect they're a large percentage of your target users).

**Comment by ibradwan** [comment]
Hi @markymc,

Thanks for your recommendation. We can definitely add this requirement to our docs page as well as the package readme file.
