### ISSUE TITLE
Can not support android API 34

### ISSUE THREAD

**Issue by censujiang** [microsoft/clarity-apps#20]
My app is built on API 34 and configured correctly as per the documentation on the Learn Microsoft website, but clarity is not receiving the data stream from my device.

But at the same time, I saw a special note in the document, which shows that Clarity only runs under the target API of 29~33. What is the problem? I don’t want to lower my API version.

**Comment by censujiang** [comment]
@ibradwan

**Comment by ibradwan** [comment]
Hello @censujiang,

Clarity currently does not support API 34. We do have plans to support it soon. So kindly stay tuned until we release a version that supports it.
