### ISSUE TITLE
500 Internal Server error  RN clarity sdk

### ISSUE THREAD

**Issue by vivek0046** [microsoft/clarity-apps#25]
![500 error 1](https://github.com/microsoft/clarity-apps/assets/77613804/91e3f07c-9720-451b-8f3b-60a3ea4bd7b9)
![500 error 2](https://github.com/microsoft/clarity-apps/assets/77613804/40aa4b01-8bb2-4e44-8b93-00d5e926c2bf)

Followed all documented steps.

anybody else facing the same issue?

**Comment by ibradwan** [comment]
@vivek0046 Thanks for reporting this, we had a few backend issues at that timeframe, but things should have stabilized soon after. Could you please confirm that the problem has been resolved on your end?

**Comment by vivek0046** [comment]
> @vivek0046 Thanks for reporting this, we had a few backend issues at that timeframe, but things should have stabilized soon after. Could you please confirm that the problem has been resolved on your end?

Hi,thanks for update 

We will try again.
