### ISSUE TITLE
When will the react native package support iOS too?

### ISSUE THREAD

**Issue by reefray** [microsoft/clarity-apps#29]
When will the react native package support iOS too?

**Comment by ibradwan** [comment]
Hello @reefray, once our iOS SDK is released, we'll work on supporting iOS on React Native apps.

**Comment by ibradwan** [comment]
We currently have an iOS package in the private preview phase, if you're interested to try it out, please reach out to us on clarity-apps-support@microsoft.com.

**Comment by enact-on** [comment]
@ibradwan any update on this? 

We have few apps we want to integrate this with.
