### ISSUE TITLE
LogLevel import not found

### ISSUE THREAD

**Issue by Renatinaveen** [microsoft/clarity-apps#3]
class ClarityConfig(
   val projectId: String,
   val userId: String? = null,
   val logLevel: LogLevel = LogLevel.None,
   val allowMeteredNetworkUsage: Boolean = false,
   val enableWebViewCapture: Boolean = true,
   val allowedDomains: String? = listOf("*")
)

**Comment by ibradwan** [comment]
It should be available to import at
```kotlin
import com.microsoft.clarity.models.LogLevel
```
Can you share your complete initialization code?
