### ISSUE TITLE
build failing on React native android

### ISSUE THREAD

**Issue by mubashiralisiddiqui** [microsoft/clarity-apps#30]
I am trying with following versions
```
React native version "react-native": "0.63.5",
"react-native-clarity": "^2.1.0",
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
  buildToolsVersion = "30.0.2"
  minSdkVersion = 23
 compileSdkVersion = 33
 targetSdkVersion = 33
```
getting error when I try to run on android
react-native-clarity/android/src/main/java/com/microsoft/clarity/reactnative/ClarityModule.kt: (80, 21): Type mismatch: inferred type is String? but String was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-clarity:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by maryamshal** [comment]
@mubashiralisiddiqui could you please share you initialization code with us?

**Comment by mubashiralisiddiqui** [comment]
<img width="765" alt="image" src="https://github.com/microsoft/clarity-apps/assets/16689214/69fe3050-f96b-4994-ae16-a403480ccb71">
@maryamshal  this is how i am initializing

**Comment by maryamshal** [comment]
Hello @mubashiralisiddiqui, 
We're investigating the error. However, please note that we officially support react-native versions > 0.64 as per this [documentation](https://learn.microsoft.com/en-us/clarity/mobile-sdk/react-native-sdk). So kindly upgrade if possible.
Regards,
Maryam
