### ISSUE TITLE
Android disable clarity when not needed

### ISSUE THREAD

**Issue by ShkurtiA** [microsoft/clarity-apps#34]
Hi,

I have seen this issue https://github.com/microsoft/clarity-apps/issues/28
but I thought to give it a try and ask this question again for another use case we have.

We have a feature where the Android app hosts a server and other devices can connect to it and consume it.
To keep the processing power free from useless actions, we do not want to have clarity enabled when this feature is running.
For this reason we need a start and stop mode for clarity.

In your documentation you mention that you disable it by default for low end devices but we can not rely only on it.

Is it possible to enable this feature?

Also we are interested in some documentation on how does clarity handle cases when the app is offline for quite some time and then goes online.
Do you have an offline mechanism?

Thank you

**Comment by ibradwan** [comment]
Hello @ShkurtiA, thanks for sharing your feedback.

Regarding the enable/disable Clarity feature, we've received multiple requests for this feature from different customers and we're prioritizing it to be released in the near future, so please stay tuned.

Regarding how Clarity handles the offline scenario:
- Clarity captures the user sessions regardless of the network status. Clarity uses the most recently fetched configs (like masking) to operate in case the device is offline.
- Data is stored in a temporary storage on the device.
- When the device comes online, the SDK starts uploading the pending data. But the session data like its timestamp and so on will be correct when you see the session on the dashboard even though it might have arrived at a later time.
- If the device did not connect to the internet for a few consecutive days, the data would be deleted automatically by the SDK (even though the data is written to a temp storage that's under the full control of the OS to remove when necessary).

**Comment by ibradwan** [comment]
@ShkurtiA We've released a new version a couple of days ago that gives you the ability to pause() and resume() Clarity whenever you need to.
