### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by iyadhuk** [microsoft/clarity-apps#35]
Getting build failures with below log

```
Could not determine the dependencies of task ':react-native-clarity:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-clarity:debugCompileClasspath'.
   > Could not find com.microsoft.clarity:clarity:2.2.0-manual20240317193429.
     Required by:
         project :react-native-clarity
```

I have added the below code in index file.

import { LogLevel, initialize } from 'react-native-clarity';

const clarityConfig = {
  logLevel: LogLevel.Verbose,
  allowMeteredNetworkUsage: true
};

initialize("**********",clarityConfig); //removed project id 

Not sure what to do here, any suggestions or responses would be great.

**Comment by yusuf-yldrm** [comment]
Hello @iyadhuk,

Thanks for pointing out the issue with the Clarity package version `2.2.0-manual20240317193429` in our `react-native-clarity` project. Could you share the errors or bugs you're experiencing? To address this, you might try using a stable version temporarily in your `build.gradle`:

Path: /node_modules/react-native-clarity/android/build.gradle file

```gradle
implementation "com.microsoft.clarity:clarity:<stable-version>"
```

Replace `<stable-version>` with a known stable version. Also, it would be helpful to report this issue to the Clarity team. We appreciate your feedback and are looking into a fix.
