### ISSUE TITLE
App crashing while opening on release build

### ISSUE THREAD

**Issue by shubhkhanna** [microsoft/clarity-apps#37]
Getting below error:
> Fatal Exception: com.facebook.react.bridge.NativeArgumentsParseException: Clarity.initialize got 9 arguments, expected 11
>        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:349)
>        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:149)
>        at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
>        at android.os.Handler.handleCallback(Handler.java:938)
>        at android.os.Handler.dispatchMessage(Handler.java:99)
>        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
>        at android.os.Looper.loop(Looper.java:236)
>        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:234)
>        at java.lang.Thread.run(Thread.java:923)
 
 "react-native": "0.73.1"
 "react-native-clarity": "^2.2.1"

**Comment by ibradwan** [comment]
Could you please share your initialization code?

**Comment by ibradwan** [comment]
It's worth noting that the Clarity package has native a component, so after upgrading the package version, you have to do a fresh build of your app.

**Comment by shubhkhanna** [comment]
Thanks @ibradwan it works for me.
