### ISSUE TITLE
Clarity support for .NET MAUI

### ISSUE THREAD

**Issue by Kebechet** [microsoft/clarity-apps#45]
https://github.com/microsoft/clarity/issues/636
https://github.com/microsoft/clarity/issues/635

**Comment by Kebechet** [comment]
I have wrapped clarity into MAUI. So you can take a look at released [nuget package](https://www.nuget.org/packages/Kebechet.Maui.MicrosoftClarity/) or the [maui repo](https://github.com/Kebechet/Maui.MicrosoftClarity)

**Comment by amralaa-MSFT** [comment]
@Kebechet Thank you for your contribution and for creating a MAUI wrapper for Clarity! We appreciate your efforts in making Clarity accessible to MAUI developers.

While we value community-driven initiatives like yours, we currently don't have plans to officially support the MAUI wrapper repository. Our development resources are primarily focused on other features and frameworks.

We wanted to clarify for those following this issue that there are no immediate plans to officially support MAUI in the near future. However, we'll continue to monitor the community's interest and needs in this area

**Comment by Kebechet** [comment]
@amralaa-MSFT thank you for the feedback. I dont have problem maintaining these wrappers and bumping lib versions from time to time so for me it is okay that you dont plan to officially support MAUI.

But I have 2 questions:
1) Could you please investigate [this issue](https://github.com/microsoft/clarity/issues/667) ? If it is really MAUI specific ...because I suppose it is some bug in your lib
2) In enum: [ApplicationFramework](https://github.com/Kebechet/Maui.MicrosoftClarity/blob/main/src/Maui.MicrosoftClarity.iOS/StructsAndEnums.cs#L6-L12) could you please add `MAUI` ? So that I would use that flag in these wrapper for you to better track usage activity ?

**Comment by omarhagoche** [comment]
> It’s hard to believe Microsoft Clarity has no plans to support MAUI, Microsoft's own framework for building cross-platform apps. Why would their analytics tool ignore their primary mobile app platform?

Yeah, they're not supporting MAUI officially, but they're fully supporting Flutter, LoL

**Comment by BarryGit17** [comment]
Bump this post - please add Clarity support for MAUI
