### ISSUE TITLE
Ionic Capacitor 

### ISSUE THREAD

**Issue by danielehrhardt** [microsoft/clarity-apps#46]
⚡️  WebView loaded

⚡️  ------ STARTUP JS ERROR ------

⚡️  ReferenceError: Can't find variable: ClarityPlugin
⚡️  URL: capacitor://localhost/main-LSHYXVST.js
⚡️  [error] - {}
⚡️  main-LSHYXVST.js:1:71819

⚡️  See above for help with debugging blank-screen issues

**Comment by danielehrhardt** [comment]
> Hi @danielehrhardt,
> 
> Could you please provide more info like:
> 
> * The steps you followed
> * The platform you're running the app on that gives you this error message
> * Your capacitor & Clarity version
> 
> Thank you!

Sure!

- Setup a new Ionic Angular Standalone Capacitor Project
- Install latest Clarity Version (npm install cordova-clarity cordova-plugin-device)
- Add the Code to the main.ts File of the Angular Application:
var success = function(message: string) {}
var failure = function(message: string) {}

declare let ClarityPlugin: any;
ClarityPlugin.initialize("-", success, failure, {isIonic: true});
- ionic cap sync

**Comment by SaadeldinBadr** [comment]
Hello @danielehrhardt,

Currently, android is the only supported platform for ionic, so make sure to move the initialization block inside a similar if condition:

```
if(Capacitor.getPlatform() === "android") {
    // Call Clarity initialize.
   ClarityPlugin.initialize("-", success, failure, {isIonic: true});
}
```

**Comment by kiranraj1430** [comment]
> > Hi [@danielehrhardt](https://github.com/danielehrhardt),
> > Could you please provide more info like:
> > 
> > * The steps you followed
> > * The platform you're running the app on that gives you this error message
> > * Your capacitor & Clarity version
> > 
> > Thank you!
> 
> Sure!
> 
> * Setup a new Ionic Angular Standalone Capacitor Project
> * Install latest Clarity Version (npm install cordova-clarity cordova-plugin-device)
> * Add the Code to the main.ts File of the Angular Application:
>   var success = function(message: string) {}
>   var failure = function(message: string) {}
> 
> declare let ClarityPlugin: any; ClarityPlugin.initialize("-", success, failure, {isIonic: true});
> 
> * ionic cap sync

What is for Angular + capacitor without Ionic framework? it will support? my case user not detected and app is getting routing conflict.
if I stayed in component A and I route to component b and if I click back button component A some parts are showing in component B like a mixing. So this issue is only happens after using this plugin.

Please give a solution or reply for my case.
