### ISSUE TITLE
Support for SPM semantic versioning (missing version tags)

### ISSUE THREAD

**Issue by TomaszLizer** [microsoft/clarity-apps#47]
Hi,
Currently repo provides clarity in form of XCFramework through Swift Package definition and as can be seen in latest commit that is in version `1.0.0`. 
However referencing Clarity in SPM by version fails since there are no tags in this repository marking particular commits with SDK version.
Adding such tags will be highly beneficial for managing dependency on Clarity :)

**Comment by amralaa-MSFT** [comment]
Thanks @TomaszLizer for your feedback. A new `1.0.0` tag has been created in this repository.
