### ISSUE TITLE
Add privacy manifest

### ISSUE THREAD

**Issue by TomaszLizer** [microsoft/clarity-apps#48]
Recently Apple started requiring `Privacy manifest` to be included in apps submitted to the App Store. Additionally all third party SDK included in app should also have their own privacy manifest (with some exemption). 
Given what Clarity iOS SDK does I assume it may actually require such privacy manifest as per Apple requirements: https://developer.apple.com/support/third-party-SDK-requirements/.

Docs on adding privacy manifest: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk#4336762

I have not yet encountered app rejection due to missing Privacy manifest, nevertheless it would be handy to have such for Clarity.

**Comment by nouranmaher86** [comment]
Thank you @TomaszLizer. We will consider to add a privacy manifest to our iOS SDKs.

**Comment by ibradwan** [comment]
Will be part of our next release.
