### ISSUE TITLE
Missing SwiftUI support

### ISSUE THREAD

**Issue by TomaszLizer** [microsoft/clarity-apps#49]
I have started testing Clarity iOS SDK from the perspective of migration from other similar tool.
First thing I noticed is that there is no `SwiftUI` support yet. Given app I am working on is built on mixed UIKit/SwiftUI environment it is crucial for us to have such support or at least predictable behaviour.
I was not able to find exact details on what does missing SwiftUI support mean, however my initial testing and observations shows few things:
- Not able to mask SwiftUI views in code
- Not able to mask SwiftUI views based on `selectors` in masking settings
- Different behaviour of SDK with regards to SwiftUI depending on iOS version, eg:
  - Every `Text` is masked in iOS 17
  - `Text` not masked in iOS 15.5

Is there any expected timeframe in which SwiftUI support will be added?
Could you provide documentation on how SDK is treating SwiftUI before official support is added?
Is it potentially unsafe to use Clarity iOS SDK with SwiftUI code (eg potential crashes, memory corruptions, etc)?

**Comment by nouranmaher86** [comment]
Hello @TomaszLizer SwiftUI will be supported in the next couple of weeks, and we will announce the release once ready so stay tuned!

**Comment by nouranmaher86** [comment]
Hi @TomaszLizer  SwiftUI is officially released in version 2.0.0. You would Need to set the
enableSwiftUI_Experimental in your SDK code.
https://learn.microsoft.com/en-us/clarity/mobile-sdk/sdk-changelog#ios-sdk-changelog

**Comment by TomaszLizer** [comment]
@nouranmaher86 @ibradwan 
Can you share some additional details on what does it mean that SwiftUI support is experimental?
Are there any potential stability issues?
Our current app relies heavily on SwiftUI so in order to consider `Clarity iOS SDK` for production environment we would need to either get official support or know something more about that :) 
Thanks in advance

**Comment by ibradwan** [comment]
Okay so given that we've recently introduced SwiftUI support, we encourage people to run some tests locally and make sure nothing is wrong before pushing to production. This is just a safety mechanism until more & more apps enable the SwiftUI support. Moving forward, the flag will be removed in one of the major releases. A note worth mentioning here is that SwiftUI support logic shares most of the logic with the UIKit support logic, and the UIKit logic has been tested and is currently being used by many apps and users.
