### ISSUE TITLE
Customised user id not reflecting in the Clarity portal

### ISSUE THREAD

**Issue by TomaszLizer** [microsoft/clarity-apps#50]
I have tried adding customised user id when running Clarity iOS SDK - I could see in Clarity logs (through Xcode) that customised user id was added correctly. 
In portal I can find `customisedUserID` field is added in details page, however it has no value assigned and I cannot filter with this id (not finding any recordings with such id).
This is one of the dealbreaker issues for me.
<img width="405" alt="Screenshot 2024-07-25 at 05 49 12" src="https://github.com/user-attachments/assets/27959088-ac07-4e8e-83cc-07fe52aea4aa">

**Comment by ibradwan** [comment]
Hi @TomaszLizer,
Thanks for sharing this issue, please provide the following details:
- Project id
- The value you used for the custom user id

Thanks

**Comment by TomaszLizer** [comment]
I have been testing that in both actual app we are aiming to deploy clarity too as well as on small isolated project.
Here is ID for the latter one: `nbw0wupcig` - this value seems to be sort of a secret, sharing this one publicly since it is just for test project, nevertheless for future reference how should we communicate issues for particular `projectID`?
When it comes to example `CustomUserId` it was different kinds:
- Plain string, eg "Tomo_test"
- UUID string
- email string
- masked email string (masked using *)

None of that worked, I have tried plain string and UUID strings for `CustomSessionID` and there it worked.

**Comment by nouranmaher86** [comment]
Thank you @TomaszLizer - We are aware of this issue and will report back when a fix is deployed. Shouldnt take long.

**Comment by ibradwan** [comment]
This should be solved now.

**Comment by TomaszLizer** [comment]
Thanks - fixed and retro-active. Can see customised user id in portal for old recordings 🙌
