### ISSUE TITLE
Missing changelogs for released Clarity versions

### ISSUE THREAD

**Issue by TomaszLizer** [microsoft/clarity-apps#51]
From the perspective of library consumer - changelogs informing me of the way Library has evolved is crucial.
Right now there are three versions of the Clarity iOS SDK release including one `major` yet no changelog provided. 
It would be very handy to have some place to look into in order to grasp what has changed and what was fixed.
I think that utilising `releases` in GitHub may be sufficient :)

**Comment by TomaszLizer** [comment]
Seems I may have missed release note for iOS SDK in documentation page:
https://learn.microsoft.com/en-us/clarity/mobile-sdk/sdk-changelog#ios-sdk-changelog
I believe this issue can be closed. However if You would like to still utilise GitHub release and link to SDK changelog documentation it would be helpful for sure! :)

**Comment by ibradwan** [comment]
Sure thanks for the valuable feedback. @amralaa-MSFT please take care of this.
