### ISSUE TITLE
[BUG][iOS] Can't build iOS app with new react native architecture v.0.74.0

### ISSUE THREAD

**Issue by serhii-yalla** [microsoft/clarity-apps#54]
**Describe the Bug**
Can't build app in XCode with new react native architecture enabled. But without I can build.

My Podfile:
```
use_frameworks! :linkage => :static
platform :ios, '13.4'

# Resolve react_native_pods.rb with node to allow for hoisting
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

prepare_react_native_project!

def pods()
#     pod 'FirebaseCoreInternal', :modular_headers => true
#     pod 'GoogleUtilities', :modular_headers => true
#     pod 'FirebaseCore', :modular_headers => true
#     pod 'GoogleTagManager', :modular_headers => true
    pod 'GoogleTagManager'
    pod 'Clarity'

    config = use_native_modules!

    setup_permissions([
        'Notifications',
    ])

    pod 'react-native-config/Extension', :path => '../node_modules/react-native-config'
    pod 'nodejs-mobile-react-native', :path => '../node_modules/nodejs-mobile-react-native'

    use_react_native!(
        :path => config[:reactNativePath],
        :app_path => "#{Pod::Config.instance.installation_root}/.."
    )
end


target '1' do
    pods()
end

target '2' do
    pods()
end

target '3' do
    pods()
end

target '4' do
    pods()
end

target '5' do
    inherit! :complete
    pods()
    # Pods for testing
end

post_install do |installer|
    config = use_native_modules!

    react_native_post_install(
        installer,
        config[:reactNativePath],
        :mac_catalyst_enabled => false,
          # :ccache_enabled => true
    )
end
```

**Repro Steps**
Just setup react-native 0.74.0, install react-native-clarity 3.0.1, enable new architecture and try to build

**Expected Behavior**
Clear build in XCode

**Screenshots**
![CleanShot 2024-08-07 at 18 29 36@2x](https://github.com/user-attachments/assets/649495be-079d-41c7-b40a-e7e79c9d4b76)

**Project Info**
If this is an issue happening in a specific Clarity project,

- Project ID (share with clarity-apps-support@microsoft.com while mentioning the issue number in the subject)

**Platform/Framework Info**

- Device: any
- OS: 17.5
- Application Framework ReactNative
- Clarity Version 3.0.1

**Comment by connorpmullins** [comment]
I'm having the same issue.

**Comment by ibradwan** [comment]
Hi there,
Unfortunately Clarity does not yet support React Native new architecture.
@amralaa-MSFT let's please add this note to the docs.

**Comment by serhii-yalla** [comment]
@ibradwan Can you tell me when to expect such an update?

**Comment by ibradwan** [comment]
Unfortunately, we have no plans to support this in the near future as the priority right now is to support Flutter.

**Comment by serhii-yalla** [comment]
> Unfortunately, we have no plans to support this in the near future as the priority right now is to support Flutter.

Thanks for the response

**Comment by amralaa-MSFT** [comment]
@serhii-yalla @connorpmullins: The build issue should be fixed if you use latest package version. Please try upgrading to react-native-calarity version 3.0.5 and performing a full clean of your project before building again.

**Comment by serhii-yalla** [comment]
@amralaa-MSFT I works! Appreciate that.

**Comment by amralaa-MSFT** [comment]
> [@amralaa-MSFT](https://github.com/amralaa-MSFT) It works! Appreciate that.

Thank you for confirming!
