### ISSUE TITLE
Maps not displayed

### ISSUE THREAD

**Issue by iostrek** [microsoft/clarity-apps#55]
Hi,

Is it possible to track user interactions with a navigation app that uses Google Maps or Apple Maps in a UIKit/SwiftUI mixed iOS application? 

Currently, the Google Map is not displaying properly—only a gray background is visible. In order to effectively test the navigation app, it’s important to understand how the user interacts with the map.

Thank you!

**Comment by amralaa-MSFT** [comment]
Thanks @iostrek. Unfortunatley, Clarity doesn't capture map contents, and this functionality isn't planned for the near future.
