### ISSUE TITLE
[BUG][Android] Jetpack compose only screen is MainActivity

### ISSUE THREAD

**Issue by IvanLarenas** [microsoft/clarity-apps#56]
im using 
`implementation 'com.microsoft.clarity:clarity-compose:2.5.0'`

The only screen that i have is MainActivity.
the setScreenName function seems to be only for React native. how to control the screen name on jetpack compose?

**Comment by SaadeldinBadr** [comment]
Hello @IvanLarenas ,

As you mentioned, setCurrentScreenName is currently only available in React Native. However, we're working on making it available for the rest, and it should be released very soon.

**Comment by SaadeldinBadr** [comment]
Hello @IvanLarenas ,

`setCurrentScreenName` is available now for android sdk too, upgrade your sdk to `clarity-compose:3.1.0` and feel free to use it.
