### ISSUE TITLE
[BUG][iOS] Crash NSInternalInconsistencyException - Failed to create remote render context

### ISSUE THREAD

**Issue by BaluNaik** [microsoft/clarity-apps#60]
**Describe the Bug**
We can see some crash logs on crashlytics dashboard

**Expected Behavior**
The app should not crash.

**Platform/Framework Info**

- Device: multiple iPhone and iPad 
- OS: iOS 17
- Application Framework Native UIKit-based 
- Clarity Version 2.0.0

**Additional Context**
Add any other context about the problem here. e.g. Nature of the issue **intermittent**

Please also add all relevant labels from the list of existing ones.

** Stack Trace **
[p_issue_cfc598765923997797ef2e15e592b3c3_crash_session_eb1bd4f363964556b7ff05dea3cc84ca_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/16845293/p_issue_cfc598765923997797ef2e15e592b3c3_crash_session_eb1bd4f363964556b7ff05dea3cc84ca_DNE_0_v2_stacktrace.txt)

**Comment by amralaa-MSFT** [comment]
Thanks @BaluNaik for reporting the issue. A similar crash was fixed in the latest version of Clarity. Could you please upgrade to Clarity v2.1.0 and let us know if your app still crashes?

Similar to: https://github.com/microsoft/clarity-apps/issues/53

**Comment by BaluNaik** [comment]
@amralaa-MSFT Thanks for the update, we are about to release the next version with the updated SDK, and I'll update the issue based on logs in the next 2/3 days.

Thanks

**Comment by BaluNaik** [comment]
@amralaa-MSFT Yes the crash is happening on the latest SDK version also. They are attached update stack trace.

Crash1: [issue_8f3902df0973c0b04b0f1ff5427b5262_crash_session_115f418d950d43e3a3a7433657ab3295_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/16920933/issue_8f3902df0973c0b04b0f1ff5427b5262_crash_session_115f418d950d43e3a3a7433657ab3295_DNE_0_v2_stacktrace.txt)

Crash2: [5c323ea0bfff01988a30fe2235ea5878_crash_session_a2767a8928cf4b2596b967bb3c91d728_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/16920934/5c323ea0bfff01988a30fe2235ea5878_crash_session_a2767a8928cf4b2596b967bb3c91d728_DNE_0_v2_stacktrace.txt)

**Comment by ibradwan** [comment]
This issue should be fixed in our latest React Native version (3.0.3).
