### ISSUE TITLE
[BUG][iOS] react-native-clarity is not using the latest version of Clarity

### ISSUE THREAD

**Issue by gronxb** [microsoft/clarity-apps#62]
**Describe the Bug**
https://github.com/microsoft/clarity-apps/issues/59

This issue also occurs in React Native.

I would like to upgrade Clarity to version 2.1.0. However, the latest version of react-native-clarity (3.0.1) is currently using Clarity 1.0.0. I believe the `react-native-clarity.podspec` file should be updated as follows:
```diff
- s.dependency "Clarity", '1.0.0'
+ s.dependency "Clarity", '2.1.0'
```
Since this code is not present in the repository, I am submitting this as an issue instead.

**Repro Steps**
X

**Expected Behavior**
I’m not sure if any modifications will be needed on the TypeScript side for the native bridge.

**Screenshots**
X

**Project Info**
react-native-clarity (3.0.1)

**Platform/Framework Info**
- Clarity Version (1.0.0)
- react-native-clarity (3.0.1)

**Additional Context**
X

**Comment by amralaa-MSFT** [comment]
@gronxb Thanks for reporting this!

We've just released a new version of `react-native-clarity`, `3.0.2`, which internally uses latest `Clarity` versio,n `2.1.0`. This should resolve the issue you're facing.

Please update your project to use `react-native-clarity` version `3.0.2`, and let us know if you encounter any further problems.

**Comment by amralaa-MSFT** [comment]
@gronxb We recommend upgrading to version `3.0.3` instead as it includes more fixes.
