### ISSUE TITLE
[REQUEST][iOS] Please open source the iOS SDK

### ISSUE THREAD

**Issue by jayvenn** [microsoft/clarity-apps#65]
Hi Microsoft Clarity Team, please open-source the iOS SDK. This allows for transparency, community support, and bug fixing without the mercy of a framework update. Please take this consideration into account. It's hyper-valuable. Thank you.

**Comment by amralaa-MSFT** [comment]
We appreciate your enthusiasm for Clarity. We've always considered making our SDKs open-source, but due to our ongoing efforts to meet customer needs and enhance Clarity's capabilities, we haven't been able to prioritize this effort.
