### ISSUE TITLE
[REQUEST][iOS]: Disable Image Sending on iOS

### ISSUE THREAD

**Issue by MichalMartinu** [microsoft/clarity-apps#66]
### Feature Request: Disable Image Sending on iOS

Hi Clarity team,

Please implement a feature to disable sending images on iOS. This is already the default behavior on Android, where a gray placeholder and an image icon represent images in recordings. Implementing this on iOS would help conserve mobile data and provide a more data-efficient experience for users.

Thank you!

**Comment by amralaa-MSFT** [comment]
@MichalMartinu 

Thanks for your suggestion!  Just to clarify, Clarity sends images on Android by default if hardware optimization is not enabled.

Here are two options to address your request using Clarity's masking featue:
- Strict Masking Mode: This masks all text and images within the recordings.
- Masking by ID/Class: Define specific elements (like image IDs or classes) that you don't want to be captured.

You can find detailed instructions on masking here: https://learn.microsoft.com/en-us/clarity/mobile-sdk/clarity-sdk-masking#ios

We appreciate your feedback on disabling image sending entirely on iOS. This is a valuable suggestion, and we'll consider it for future development.
