### ISSUE TITLE
[BUG][iOS] Crash when full screen video orientation changes

### ISSUE THREAD

**Issue by aybarska** [microsoft/clarity-apps#67]
**Describe the Bug**
We use a video player (AVPlayer) with controls. When user in the full screen mode and after make some orientation changes. The app is crashing. Only happens when clarity is active. I will provide the stack trace.  

**Repro Steps**
Add clarity to project Add AVPlayer with full screen capability and enable device orientation. rotate device few times. 

**Expected Behavior**
Should not be crash

**Project Info**
ios

- Project ID mailed to clarity-apps-support@microsoft.com with issue number

**Platform/Framework Info**

- Device:  iPhone 13, iPhone XR
- OS: iOS 17.6.1
- Application Framework: Native UIKit-based
- Clarity Version: 2.0.0

**Additional Context**
Adding the stacktrace from firebase crashlytics.

[crash_session_a9a2f2e7c1d34b599c3f96219c589c7d_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/17055871/crash_session_a9a2f2e7c1d34b599c3f96219c589c7d_DNE_0_v2_stacktrace.txt)

**Comment by amralaa-MSFT** [comment]
@aybarska Thank you for reporting this issue. We will look into it further. Meanwhile, could you please try using latest Clarity version `2.1.2` and let us know if it still crashes?

**Comment by aybarska** [comment]
@amralaa-MSFT hi, we just tried `2.1.2` unfortunately its still crashing

**Comment by amralaa-MSFT** [comment]
@aybarska Thank you for confirmation. I was able to reproduce the crash and I'm currently working on a fix.

**Comment by koliush2018** [comment]
Same problem, with fullscreen AVPlayerViewController presenting via UIViewControllerRepresentable

**Comment by koliush2018** [comment]
@aybarska try to rotate the screen on the main thread with some delay. seems it helps me

**Comment by ibradwan** [comment]
Hi,

This issue should be resolved in iOS SDK version 2.2.2. Please upgrade and let us know if you have any feedback.

**Comment by aybarska** [comment]
No crash on version 2.2.2, thx
