### ISSUE TITLE
[IOS] NSInvalidArgumentException: Attempt to add script message handler with name 'clarityMessageHandler6156' when one already exists.

### ISSUE THREAD

**Issue by LIND96** [microsoft/clarity-apps#68]
In my application there was an error when implementing Clarity on iOS, 

[IOS] NSInvalidArgumentException: Attempt to add script message handler with name 'clarityMessageHandler6156' when one already exists.

any suggestions on how to fix it?

**Comment by amralaa-MSFT** [comment]
@LIND96 I assume your app uses an older version of Clarity. Could you please upgrade to latest Clarity version `2.1.1` and let us know if your app still crashes?

**Comment by LIND96** [comment]
hello @amralaa-MSFT  in my project using react-native-clarity 3.0.1

**Comment by LIND96** [comment]
okay maybe I should upgrade the react-native-clarity version to 3.0.4

**Comment by LIND96** [comment]
thanks bro @amralaa-MSFT
