### ISSUE TITLE
Clarity encountered an error - Cannot read properties of undefined (reading 'selector')

### ISSUE THREAD

**Issue by YadhuYk007** [microsoft/clarity-apps#69]
**Describe the Bug**
Clarity encountered an error - _Cannot read properties of undefined (reading 'selector')_

**Repro Steps**
Login to account >> open project >> recordings >> select one recording to play >> error screen

**Expected Behavior**
Login to account >> open project >> recordings >> select one recording to play >> playback

**Screenshots**
<img width="572" alt="Screenshot 2024-09-27 at 5 11 45 PM" src="https://github.com/user-attachments/assets/a3016abf-e228-40da-9a24-10e0bc090fa8">

**Project Info**
React Native project

- Project ID (share with clarity-apps-support@microsoft.com while mentioning the issue number in the subject)

**Comment by amralaa-MSFT** [comment]
@YadhuYk007 Please send your project ID to clarity-apps-support@microsoft.com mentioning this issue's ID

**Comment by YadhuYk007** [comment]
It's resolved now. Thanks
