### ISSUE TITLE
[Exception][iOS] Bug Report

### ISSUE THREAD

**Issue by ghadeermohameedelmahdy** [microsoft/clarity-apps#70]
**Describe the Bug**
Firebase crachlaytics could detect exception EXC_BAD_ACCESS in displayListQueue.

**Screenshots**
<img width="551" alt="Screenshot 2024-09-29 at 4 42 32 PM" src="https://github.com/user-attachments/assets/b7b8be09-3e5e-49b2-b47f-9c284fa2e54c">

**Platform/Framework Info**

- Device: [iPhone 14 PLus]
- OS: [iOS 17.6.1]
- Application Framework [Native UIKit-based ]
- Clarity Version [1.0.0]

**Comment by amralaa-MSFT** [comment]
Thanks @ghadeermohameedelmahdy for reporting the issue. Similar crashes were fixed in more recent Clarity versions. Could you please upgrade to Clarity version `2.1.2` and let us know if it eliminates these crashes?

**Comment by amralaa-MSFT** [comment]
We haven't heard back from you in a while regarding trying the latest version. We'll close this issue for now, but please feel free to reopen it if you have any further questions or need additional assistance.
