### ISSUE TITLE
[BUG][Android] Clarity is not catching errors in a React Native app

### ISSUE THREAD

**Issue by bbernag** [microsoft/clarity-apps#73]
**Describe the Bug**
I'm not seeing any errors in the Dashboard, I intentionally crash the app in development mode and also creating a release build

**Screenshots**
![Image](https://github.com/user-attachments/assets/e0d11e23-70d2-494b-822d-cc838734e024)

**Platform/Framework Info**

- Device: Android Emulator
- OS: Android 10.0 arm64-v8a
- Application Framework: React Native
  - v0.74.3
  - newArchEnabled=false
  - hermesEnabled=true
- Clarity Version: 3.0.5 and 3.1.1

**Additional Context**
The errors I tried were:

- Text strings must be rendered within a <Text> component
- Cannot read property of undefined
- throw new Error('testing clarity error reporting');

All errors quit the app, in logcat I can see all the event logs being tracked but I don't see any error event tracked

**Comment by ibradwan** [comment]
Hi @bbernag,

Thanks a lot for reporting this issue, a new version will be shipped soon to address this issue among others.

**Comment by ibradwan** [comment]
This issue should be resolved in the latest version "4.0.4".
