### ISSUE TITLE
Screen name in SwiftUI is very hard to use

### ISSUE THREAD

**Issue by rakefetWorkiz** [microsoft/clarity-apps#79]
Using SwiftUI the default screen name is generated by the root view having a long generated name similar to that: `UIHostingController<ModifiedContent<AnyView, RootModifier>>`

Even using the `ClaritySDK.setCurrentScreenName` function, it's still very difficult to use in the clarity dashboard, since the custom name is added a the end of this generated long name, which is not visible within the default view 
So in order to see which screen the user actually visited you need to hover for few seconds on each screen visited event. Not very practical.
![Image](https://github.com/user-attachments/assets/17b3c443-16a3-4bfe-9e6e-62ad8c039028)

heat-map also seem to not be very usable
![Image](https://github.com/user-attachments/assets/6066c903-68a9-4f70-a291-1e345f0cf53d)

**Comment by ibradwan** [comment]
Hello @rakefetWorkiz,

Thanks for reaching out with this feedback. We're aware of this problem and we'll be working on a front-end change that makes it more usable.

**Comment by amralaa-MSFT** [comment]
@rakefetWorkiz: Thanks for your patience and understanding.

We're excited to announce that we've addressed the issue of long, unreadable screen names in Clarity v3.0.2. Upgrading to this version will resolve this problem.

To clarify, previous sessions will retain their long names, but any new sessions initiated after the upgrade will display the custom screen names you've set using `ClaritySDK.setCurrentScreenName`.
