### ISSUE TITLE
Screen name in react-native

### ISSUE THREAD

**Issue by moh3n9595** [microsoft/clarity-apps#8]
In `react-native-clarity`, the screen name is always logged as `MainActivity`. Is any way to change this behavior?

**Comment by nouranmaher86** [comment]
We are working on supporting sub screens and fragments with our next Clarity release. Stay tuned!

**Comment by danotavio** [comment]
Excited to see this feature!

**Comment by PhilipBrew** [comment]
Looking forward to this feature too!

**Comment by felipejoribeiro** [comment]
Looking forward on this features as well!

**Comment by Andreesch** [comment]
Awesome initiative to improve UX in RN apps 🤩

**Comment by nouranmaher86** [comment]
Hello - We have this feature in testing now - we would like to solicit some customer feedback before rolling it out to PROD - if you're interested to try it - please send me an email on nouranmaher@microsoft.com

**Comment by ibradwan** [comment]
This has been addressed in 1.0.1 please upgrade and let us know your experience.
